### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by Mahsa0M** [SakurajimaMaiii/ProtoKD#2]
Hi,

I was trying to run your code and noticed that in train_protokd.py, you are trying to import contrastive_loss and kd_loss from loss.py, but these don't exist in loss.py. These losses are not used in the main part of the train_protokd script and omitting their import statement will solve the issue. But I thought to point it out just in case :)

Best,
Mahsa

**Comment by SakurajimaMaiii** [comment]
Thanks for pointing this. I have fixed this bug. Thank you!
