### ISSUE TITLE
A sugestion of updating the code of ShaSpec paper

### ISSUE THREAD

**Issue by billhhh** [SakurajimaMaiii/ProtoKD#4]
A awesome project! Thank you for organizing all these and include our ShaSpec paper https://arxiv.org/abs/2307.14126 "Multi-modal Learning with Missing Modality via Shared-Specific Feature Modelling". It is open sourced and the code is available at https://github.com/billhhh/ShaSpec. Could you update the code of the paper?

**Comment by SakurajimaMaiii** [comment]
Thanks for your reminder, it has been updated ！
